SELECT CUSTNO,CUSTNAME,PHONE,CITY FROM CourseraDatabase.CUSTOMER;

SELECT CUSTNO, CUSTNAME, PHONE, CITY 
FROM CourseraDatabase.CUSTOMER CUSTOMER
WHERE CUSTOMER.STATE = 'CO';

SELECT * 
FROM CourseraDatabase.EVENTREQUEST AS ER
WHERE ESTCOST > '4000'
ORDER BY ER.DATEHELD;

SELECT EVENTNO, DATEHELD
FROM CourseraDatabase.EVENTREQUEST AS ER
WHERE (STATUS = 'Approved' AND ESTAUDIENCE > '9000') OR (STATUS='pending' AND ESTAUDIENCE > '7000');